#ifndef __NPE_GEM_HCI_SERIAL_INTERFACE__
#define __NPE_GEM_HCI_SERIAL_INTERFACE__
#include <stdint.h>

uint32_t npe_gem_hci_library_interface_init(void);
uint32_t npe_hci_library_send_ping(void);
uint32_t npe_hci_library_send_command_bluetooth_config_set_device_name(utf8_data_t* bluetoothName);
uint32_t npe_hci_library_send_command_bluetooth_info_set_manufacturer_name(utf8_data_t* manufacturer_name);
uint32_t npe_hci_library_send_command_bluetooth_info_set_model_number(utf8_data_t* model_number);
uint32_t npe_hci_library_send_command_bluetooth_info_set_serial_number(utf8_data_t* serial_number);
uint32_t npe_hci_library_send_command_bluetooth_info_set_hardware_rev(utf8_data_t* hardware_revision);
uint32_t npe_hci_library_send_command_bluetooth_info_set_firmware_rev(utf8_data_t* firmware_revision);
uint32_t npe_hci_library_send_command_bluetooth_info_set_battery_included(uint8_t battery_included);
uint32_t npe_hci_library_send_command_gymconnect_set_supported_equipment_control_features(uint32_t equipment_control_field_identifier);
#endif